required = ["k8s.io/gengo/types", "k8s.io/code-generator/cmd/client-gen"]

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "github.com/json-iterator/go"
    non-go = false
    go-tests = false
    unused-packages = false

  [[prune.project]]
    name = "k8s.io/code-generator"
    non-go = false
    go-tests = false
    unused-packages = false
  
  [[prune.project]]
    name = "k8s.io/gengo"
    non-go = false
    go-tests = false
    unused-packages = false

[[constraint]]
  name = "github.com/coreos/ignition"
  version = "0.26.0"

# [[constraint]]
#   name = "github.com/coreos/container-linux-config-transpiler"
#   version = "v0.9.0"


# [[constraint]]
#   name = "github.com/ghodss/yaml"
#   version = "v1.0.0"

# [[constraint]]
#   name = "github.com/golang/glog"
#   revision = "44145f04b68cf362d9c4df2182967c2275eaefed"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.1"

# [[constraint]]
#   name = "k8s.io/client-go"
#   version = "8.0.0"

[[override]]
  name = "github.com/json-iterator/go"
  version = "1.1.3"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.11.1"

[[override]]
  name = "k8s.io/gengo"
  revision = "fdcf9f9480fdd5bf2b3c3df9bf4ecd22b25b87e2"

# [[constraint]]
#   name = "github.com/Masterminds/sprig"
#   version = "v2.15.0"

# [[constraint]]
#   name = "github.com/OneOfOne/xxhash"
#   version = "v1.2.1"
