apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: worker
  namespace: {{.TargetNamespace}}
spec:
  machineConfigSelector:
    matchLabels:
      "machineconfiguration.openshift.io/role": "worker"
  machineSelector:
    matchLabels:
      node-role.kubernetes.io/worker: ""