mode: 0755
path: "/etc/kubernetes/static-pod-resources/keepalived/scripts/chk_default_ingress.sh.tmpl"
contents:
  inline: |
    #!/bin/bash
    /host/bin/oc --kubeconfig /var/lib/kubelet/kubeconfig get ep -n openshift-ingress router-internal-default -o json | jq -e '.subsets[].addresses | map( select (.ip == "{{`{{.NonVirtualIP}}`}}") )[0]' >/dev/null
