name: "setup-etcd-environment.service"
enabled: true
contents: |
  [Unit]
  Description=Setup Etcd Environment  
  Requires=network-online.target  
  After=network-online.target

  [Service]
  Restart=on-failure
  RestartSec=5s

  ## FIXME(abhinav): switch this to official image.
  Environment="IMAGE=docker.io/abhinavdahiya/origin-setup-etcd-environment"

  ExecStartPre=/usr/bin/mkdir --parents /run/etcd
  ExecStart=/bin/podman \
    run \
      --net host \
      --rm \
      --volume /run/etcd:/run/etcd:z \
      ${IMAGE} \
        --discovery-srv={{.ClusterName}}.{{.BaseDomain}} \
        --output-file=/run/etcd/environment \
        --v=4 \

  [Install]
  WantedBy=multi-user.target
