apiVersion: v1
kind: ConfigMap
metadata:
  name: machine-config-operator-images
  namespace: openshift-machine-config-operator
data:
  images.json: >
    {
      "machineConfigOperator": "registry.svc.ci.openshift.org/openshift:machine-config-operator",
      "etcd": "registry.svc.ci.openshift.org/openshift:etcd",
      "infraImage": "registry.svc.ci.openshift.org/openshift:pod",
      "kubeClientAgentImage": "registry.svc.ci.openshift.org/openshift:kube-client-agent"
    }
